### ISSUE TITLE
GATE converters (lif2gate / gate2lif) mal-function.

### ISSUE THREAD

**Issue by mhabsaoui** [brandeis-nlp/edu.brandeis.cs.gate#1]
Hi,

About the WS archives, i just wanted to report a mal-functionning (if i'm not wrong) of the GATE converters (lif2gate / gate2lif) : as we need to use theses converters, it seems thers's an error in conversion, related with the discriminator that is written in the resulted lif container : TEXT instead of JSONLD/LIF... even if it' ok (in green) for processing.
![image](https://user-images.githubusercontent.com/18755135/26918717-69effc0a-4c33-11e7-8c74-7df6f3a290af.png)

**Comment by ksuderman** [comment]
There are a few issues:

1. The "Wrap data" tool, despite the labelling, does not actually create the format the Lif2Gate converter is expecting so the converter returns an error message.
1. As far as Galaxy is concerned the converter did behave as expected; it didn't throw an exception and it returned a well formed JSON document. That JSON document contained an error message, but to Galaxy everything went as expected so the output was green in the history. 
1. All of the ~~tools~~ tokenizers should accept the "5: Output"  item as input so there is no real need to do an explicit conversion at that point.
1. Newer versions of LAPPS/Galaxy typically do not require users to insert converters explicitly into a workflow; Galaxy should figure out where format conversion is required and insert a converter automatically if one is available.

We are currently in the process of rolling out updated versions of most services and we will be updating everything over the next several weeks/months.

**Comment by mhabsaoui** [comment]
Hi @ksuderman and thanks for your feedback again !

> All of the tools tokenizers should accept the "5: Output" item as input so there is no real need to do an explicit conversion at that point.

In fact, with the gates_services v200, when we try to connect the output of the "Wrap data" tool to the Gate tokenizer => it refuses to connect (the small arrow in green doesn't appear in workflow editor), as it only accepts gate format according to galaxy wrapper setting...

Whereas with v210/v220, it seems it connects, but after some test it works not well :

![image](https://user-images.githubusercontent.com/18755135/27542690-53296228-5a88-11e7-9adf-8df4b23b92b4.png)


![image](https://user-images.githubusercontent.com/18755135/27541280-a527bb74-5a83-11e7-9f98-663ca3aad420.png)


`{"discriminator":"http://vocab.lappsgrid.org/ns/error","payload":"Unable to execute the Sentence Splitter.\norg.lappsgrid.api.InternalException: Unknown document type : http://vocab.lappsgrid.org/ns/error\n\tat org.anc.lapps.gate.SimpleGateService.getDocum
ent(SimpleGateService.java:297)\n\tat org.anc.lapps.gate.SimpleGateService.doExecute(SimpleGateService.java:242)\n\tat org.anc.lapps.gate.SimpleGateService.doExecute(SimpleGateService.java:255)\n\tat org.anc.lapps.gate.SentenceSplitter.execute(SentenceSpli
tter.java:34)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\
n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat jp.go.nict.langrid.servicecontainer.decorator.ServiceInvoker.invoke(ServiceInvoker.java:39)\n\tat jp.go.nict.langrid.servicecontainer.decorator.FirstDecoratorChain.next(FirstDecoratorChain.java:4
9)\n\tat jp.go.nict.langrid.servicecontainer.handler.ServiceInvocationHandler.invoke(ServiceInvocationHandler.java:29)\n\tat com.sun.proxy.$Proxy375.execute(Unknown Source)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect`

![image](https://user-images.githubusercontent.com/18755135/27541748-63e62e3c-5a85-11e7-9c80-560a9b10746e.png)



> We are currently in the process of rolling out updated versions of most services and we will be updating everything over the next several weeks/months.

cool, good to hear :+1: 


PS:  I just wanted to alert about (if i'm not wrong) an error on galaxy wrapping for Gate tools on Develop branch : There is a shift between the names from galaxy wrapping / service package download & service implementation...

![image](https://user-images.githubusercontent.com/18755135/27544220-c557abbc-5a8c-11e7-933f-c187a6c2c5d7.png)

![image](https://user-images.githubusercontent.com/18755135/27544257-dc7ab47e-5a8c-11e7-992a-1e2c3ccae2be.png)

![image](https://user-images.githubusercontent.com/18755135/27544313-0fa13b16-5a8d-11e7-8cd8-8013805ce9f1.png)

**Comment by mhabsaoui** [comment]
Hi,

I'm following my tests to understand how Gate Tool is working. I've got 2 ways of working :

- I have to start the Gate Workflow with the Tokenizer (must be set just after the output of wrap-data
 Tool, and not the SentenceSplitter ) to make all the pipeline of tools work without error.

![image](https://user-images.githubusercontent.com/18755135/27820153-b8156252-609d-11e7-84f9-c8296a7d97c7.png)

- Modify manually the output type of wrap-data to 'gate' format :

![image](https://user-images.githubusercontent.com/18755135/27823973-38571200-60ab-11e7-8e98-7e6762be471f.png)

![image](https://user-images.githubusercontent.com/18755135/27824126-ac2d4672-60ab-11e7-8033-04f5f1f902a2.png)

**Comment by ksuderman** [comment]
The GATE tools need to be run in a specific order;  tokenizer, sentence splitter, then the pos tagger. The tools on http://galaxy.lappsgrid.org do a better job of explaining the requirements of each tool and
 I am in the process of updating the wrappers used in appliances.

Note: when you change the datatype in Galaxy that does not actually change the format of the file, just what Galaxy thinks the format is.

**Comment by mhabsaoui** [comment]
Hi,

> The GATE tools need to be run in a specific order; tokenizer, sentence splitter, then the pos tagger

Why is that so specific to GATE, whereas we can set the sentence splitter first with no problem for other Tools (Stanford, OpenNLP...) ? 
Is it because only the Tokonizers automatically convert the input (text file) as first Tool (in a pipeline) to the jsonld/lif format ?

PS: recommended order from linguist people we're working with here is to start splitting sentences (split -> tokenize -> POSTagg -> Any other (NER / Chunkers / Gazetter /  ). But Tokenizing first is OK :+1: 

> Note: when you change the datatype in Galaxy that does not actually change the format of the file, just what Galaxy thinks the format is.

Thanks for this accuracy, I wouldn't have notice it at all. I'll keep it in mind !

>  I am in the process of updating the wrappers used in appliances.

Nice. I suppose then I can already start playing around with GateServices-v230.

Keep up the good work :+1: 

Cheers.

**Comment by ksuderman** [comment]
> Why is that so specific to GATE, whereas we can set the sentence splitter first with no problem for other Tools (Stanford, OpenNLP...) ?

It depends on the tool and wrapper implementation. For example, the Stanford "tokenizer" provided by Weblicht [1] (a group in Germany) produces both tokens and sentence annotations, while our implementation [2] only produces tokens and a separate sentence splitter is required to get sentence annotations.

1. http://api.lappsgrid.org/metadata?id=anc:weblicht.stanford.tokenizer_1.0.0
2. http://api.lappsgrid.org/metadata?id=anc:stanford.tokenizer_2.0.0
